apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq2
  labels:
    app: rocketmq2

spec:
  serviceName: rocketmq2
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq2
  template:
    metadata:
      labels:
        app: rocketmq2
    spec:
      containers:
        - name: rocketmq
          image: pilgrima/rocketmq:broker-4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT
              value: -Duser.home=/home/rocketmq
            - name: JAVA_OPT_EXT
              value:  -Xmn256m
          command: ["sh","mqnamesrv"]
          ports:
            - containerPort: 9876
          volumeMounts:
            - name: vol-logs
              mountPath: /home/rocketmq/logs
            - name: vol-store
              mountPath: /home/rocketmq/store
        - name: rmqbroker
          image: pilgrima/rocketmq:broker-4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 440m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Duser.home=/home/rocketmq -Xmx2048M -Xms1024M -Xmn256m
          command: [ "sh","mqbroker","-c","/etc/rocketmq/broker-b.conf","autoCreateTopicEnable=true" ]
          ports:
            - containerPort: 10959
            - containerPort: 10961
            - containerPort: 10962
          volumeMounts:
            - name: vol-logs-a
              mountPath: /home/rocketmq/logs
            - name: vol-store-a
              mountPath: /home/rocketmq/store
            - name: vol-conf
              mountPath: /etc/rocketmq/
        - name: rmqbroker-slave
          image: pilgrima/rocketmq:broker-4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Duser.home=/home/rocketmq -Xmx2048M -Xms1024M -Xmn256m
          command: [ "sh","mqbroker","-c","/etc/rocketmq/broker-b-s.conf","autoCreateTopicEnable=true" ]
          ports:
            - containerPort: 10969
            - containerPort: 10971
            - containerPort: 10972
          volumeMounts:
            - name: vol-logs-as
              mountPath: /home/rocketmq/logs
            - name: vol-store-as
              mountPath: /home/rocketmq/store
            - name: vol-conf
              mountPath: /etc/rocketmq/
        - name: rmqbroker-slave2
          image: pilgrima/rocketmq:broker-4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: -Duser.home=/home/rocketmq -Xmx2048M -Xms1024M -Xmn256m
          command: [ "sh","mqbroker","-c","/etc/rocketmq/broker-b-s2.conf","autoCreateTopicEnable=true" ]
          ports:
            - containerPort: 10979
            - containerPort: 10981
            - containerPort: 10982
          volumeMounts:
            - name: vol-logs-as2
              mountPath: /home/rocketmq/logs
            - name: vol-store-as2
              mountPath: /home/rocketmq/store
            - name: vol-conf
              mountPath: /etc/rocketmq/
      volumes:
        - name: vol-logs
          hostPath:
            path: /data1/rocketmq/logs-2
            type: DirectoryOrCreate
        - name: vol-store
          hostPath:
            path: /data1/rocketmq/store-2
            type: DirectoryOrCreate
        - name: vol-conf
          configMap:
            name: rocketmq-config
        - name: vol-logs-a
          hostPath:
            path: /data1/rocketmq/logs-2b
            type: DirectoryOrCreate
        - name: vol-store-a
          hostPath:
            path: /data1/rocketmq/store-2b
            type: DirectoryOrCreate
        - name: vol-logs-as
          hostPath:
            path: /data1/rocketmq/logs-2bs
            type: DirectoryOrCreate
        - name: vol-store-as
          hostPath:
            path: /data1/rocketmq/store-2bs
            type: DirectoryOrCreate
        - name: vol-logs-as2
          hostPath:
            path: /data1/rocketmq/logs-2bs2
            type: DirectoryOrCreate
        - name: vol-store-as2
          hostPath:
            path: /data1/rocketmq/store-2bs2
            type: DirectoryOrCreate