apiVersion: v1
kind: Service
metadata:
  name: rocketmq1-ns
  labels:
    app: rocketmq1-ns
spec:
  type: NodePort
  ports:
    - port: 9876
      targetPort: 9876
      nodePort: 30008
      name: rmqser
  selector:
    app: rocketmq1


apiVersion: v1
kind: Service
metadata:
  name: rocketmq1-broker
  labels:
    app: rocketmq1-broker
spec:
  type: ClusterIP
  ports:
    - port: 9876
    - port: 10911
      targetPort: 10911
      name: rmqbroker
    - port: 10921
      targetPort: 10921
      name: rmqbrokerslave
    - port: 10931
      targetPort: 10931
      name: rmqbrokerslave2
  selector:
    app: rocketmq1