apiVersion: v1
kind: Service
metadata:
  name: rocketmq2
  labels:
    app: rocketmq2
spec:
  type: ClusterIP
#指定IP地址
  clusterIP: 10.111.64.219
  ports:
    - port: 9876
      targetPort: 9876
      name: rmqns2
    - port: 10961
      targetPort: 10961
      name: rmqbroker2
    - port: 10971
      targetPort: 10971
      name: rmqbrokerslave2
    - port: 10981
      targetPort: 10981
      name: rmqbrokerslave22
  selector:
    app: rocketmq2