apiVersion: v1
kind: Service
metadata:
  name: rocketmq1
  labels:
    app: rocketmq1
spec:
  type: ClusterIP
#指定IP地址
  clusterIP: 10.111.64.218
  ports:
    - port: 9876
      targetPort: 9876
      name: rmqns
    - port: 10911
      targetPort: 10911
      name: rmqbroker
    - port: 10921
      targetPort: 10921
      name: rmqbrokerslave
    - port: 10931
      targetPort: 10931
      name: rmqbrokerslave2
  selector:
    app: rocketmq1