apiVersion: v1
kind: Service
metadata:
  name: fdfs1-ngx
  labels:
    app: fdfs1-ngx
spec:
  type: NodePort
  ports:
  - name: group1
    port: 8888
    targetPort: 8888
    nodePort: 30009
  - name: group2
    port: 8889
    targetPort: 8889
    nodePort: 30010
  selector:
    app: fdfs1

---

apiVersion: v1
kind: Service
metadata:
  name: fdfs2-ngx
  labels:
    app: fdfs2-ngx
spec:
  type: NodePort
  ports:
  - name: group1
    port: 8888
    targetPort: 8888
    nodePort: 30011
  - name: group2
    port: 8889
    targetPort: 8889
    nodePort: 30012
  selector: 
    app: fdfs2
